#!/usr/bin/env python

Import('env')

env.add_source_files(env.modules_sources, "*.cpp") #this will add all the cpp files
env.add_source_files(env.modules_sources, "core/*.cpp")

env.add_source_files(env.modules_sources, "BT/*.cpp")
env.add_source_files(env.modules_sources, "BT/Nodes/*.cpp")
env.add_source_files(env.modules_sources, "BT/Nodes/Composite/*.cpp")
env.add_source_files(env.modules_sources, "BT/Nodes/Leaf/*.cpp")
env.add_source_files(env.modules_sources, "GOAP/*.cpp")
env.add_source_files(env.modules_sources, "HSM/*.cpp")
env.add_source_files(env.modules_sources, "SAI/*.cpp")
env.add_source_files(env.modules_sources, "SAI/behaviors/*.cpp")

env.add_source_files(env.modules_sources, "scene/*.cpp")
env.add_source_files(env.modules_sources, "editor/*.cpp")
